/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PostCard {
        "body": string;
        "title": string;
    }
    interface PostList {
        "posts": any[];
    }
}
declare global {
    interface HTMLPostCardElement extends Components.PostCard, HTMLStencilElement {
    }
    var HTMLPostCardElement: {
        prototype: HTMLPostCardElement;
        new (): HTMLPostCardElement;
    };
    interface HTMLPostListElement extends Components.PostList, HTMLStencilElement {
    }
    var HTMLPostListElement: {
        prototype: HTMLPostListElement;
        new (): HTMLPostListElement;
    };
    interface HTMLElementTagNameMap {
        "post-card": HTMLPostCardElement;
        "post-list": HTMLPostListElement;
    }
}
declare namespace LocalJSX {
    interface PostCard {
        "body"?: string;
        "title"?: string;
    }
    interface PostList {
        "posts"?: any[];
    }
    interface IntrinsicElements {
        "post-card": PostCard;
        "post-list": PostList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "post-card": LocalJSX.PostCard & JSXBase.HTMLAttributes<HTMLPostCardElement>;
            "post-list": LocalJSX.PostList & JSXBase.HTMLAttributes<HTMLPostListElement>;
        }
    }
}
